name = "cc-flipper-relay"
main = "worker.js"
compatibility_date = "2026-05-01"
workers_dev = true

[[durable_objects.bindings]]
name = "MAILBOX"
class_name = "Mailbox"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Mailbox"]
